### ISSUE TITLE
Definition entity and extractor

### ISSUE THREAD

**Issue by dykang** [allenai/scholar-reader#122]
Implement a new entity `definition` to store term and definition pairs predicted by NLP+ML backend system. The codes will be stored under `entities/`. Initial commits will be pushed in [dykang/definition_extractor](https://github.com/allenai/scholar-reader/tree/dykang/definition_extractor).

- [x] initial skeleton following other entities
- [x] featurization for NLP pipeline using spacy and scispacy
- [x] load/inference term/definition prediction using pre-trained transformer models
- [x] additional features related to definitions: colorization, etc (need @andrewhead's help)
- [ ] integration with @rayfok's term entity UI code (refer to #123 )
- [x] formatting (black, mypy)
- [ ] testing
    - [x] checking definitions are correctly extracted from sentences
    - [x] checking definition entities are uploaded in database schema
    - [ ] checking definitions are rendered in UI
- [x] model downloader
- [x] inference batching for speed-up
- [ ] separate csv files for terms and definitions
- [ ] aggregation over terms/definitions (e.g., coreference links)
     - [ ] find links across every term in a paper and links across every definition in a paper
- [ ] update docker file for dependencies
- [ ] add model location in README.md and config.ini

**Comment by dykang** [comment]
Need README instruction for those who like to contribute to making a new entity type.

**Comment by dykang** [comment]
Need a batching to process multiple sentences together for increasing speed. Also, the module needs to automatically download the pre-trained model from the server and load it if it doesn't exist.

**Comment by andrewhead** [comment]
Sweet! So excited to see this! Regarding this item:

> additional features related to definitions: colorization, etc (need @andrewhead's help)

Is there anything that would help to chat through right now?

**Comment by dykang** [comment]
Please see #125 regarding the code review.
