### ISSUE TITLE
Live demo?

### ISSUE THREAD

**Issue by mojesty** [allenai/scholar-reader#18]
Hello! This looks like a nice work, however i'm limited in resources and therefore it's very difficult to process lots of PDFs on my machine. Is there a web demo of the scholar reader?

**Comment by andrewhead** [comment]
Hey @mojesty! Apologies for the late reply, and I'm glad to hear of your interest :-). This project is an early alpha, so there isn't really a public web demo just yet. You can expect to find a fully working version online in the near future.

**Comment by mojesty** [comment]
@andrewhead could you please tell approximate time when a working version will be available? Is it a matter of weeks, months?

**Comment by andrewhead** [comment]
Good question, @mojesty! We're currently looking at the timeline on the order of months, I'm hoping the middle of this year.
