### ISSUE TITLE
Easier way to close the side bar

### ISSUE THREAD

**Issue by andrewhead** [allenai/scholar-reader#26]
Users want an easier way to close the side bar (i.e. the one that contains lists of paper abstracts).

Currently, the side bar can be closed by scrolling to the top and clicking the left chevron, or by typing Escape. The first one feels annoying, and the second option is unknown to most users. Perhaps we should make the chevron "sticky" so that it can be used at any time to dismiss the side bar.

We may also might want to make it possible to close the sidebar by clicking outside of it.

**Comment by zkirby** [comment]
Thoughts on just clicking outside of the sidebar to close it? This feels the most natural to me personally and I was a little confused when the side bar didn't behave that way.

**Comment by andrewhead** [comment]
Agreed, that sounds natural to me! If we went with that, I think we should also include some button that's always visible in the sidebar in case someone is looking for a "close" button.

**Comment by zkirby** [comment]
Also just to clarify, I can work on this issue as well :)

**Comment by zkirby** [comment]
Diving into this a little deeper, should the draw close when you select another symbol? I am unsure about what that interaction should be

**Comment by andrewhead** [comment]
Good question! I think that sounds like a suitable behavior. Let's implement that and see how it feels.
