### ISSUE TITLE
Don't disable navigation links from the original paper

### ISSUE THREAD

**Issue by andrewhead** [allenai/scholar-reader#33]
Users wanted to click on links in the paper (particularly to jump from figure references to those figures), though they couldn't because the UI code disables the default annotation layers that contain such links.

The ideal behavior is to enable the other annotation layers, and disable only those annotations in the other layers that overlap substantially with the ones we create.

**Comment by andrewhead** [comment]
Tasks for @jocelynzsun:

- [ ] Un-disable the links for figures, tables, and appendices
- [ ] Selectively disable the links for figures, tables, and appendices. As noted above:

> The ideal behavior is to enable the other annotation layers, and disable only those annotations in the other layers that overlap substantially with the ones we create.

**Comment by andrewhead** [comment]
@jocelynzsun I have a design question following on your recent code update? If we have _no_ citation links for a paper (i.e. we haven't processed the paper in our backend), should we:

1. show the pdf.js links, or 
2. still disable the pdf.js citation links?

Option 1 still provides some helpful functionality the authors might have wanted to be available to users for navigating papers. Option 2, however, would make sure that citation-click behavior is consistent across papers (either you see the tooltip, or you see nothing). Which one do you think is best?

**Comment by jocelynzsun** [comment]
> @jocelynzsun I have a design question following on your recent code update? If we have _no_ citation links for a paper (i.e. we haven't processed the paper in our backend), should we:
> 
> 1. show the pdf.js links, or
> 2. still disable the pdf.js citation links?
> 
> Option 1 still provides some helpful functionality the authors might have wanted to be available to users for navigating papers. Option 2, however, would make sure that citation-click behavior is consistent across papers (either you see the tooltip, or you see nothing). Which one do you think is best?

We had a brief discussion over this last tuesday, I think it would be better if we still disable the pdf.js citation links to make the behavior consistent. I imagine it could be confusing if clicking on some citations a tooltip is produced but the paper jumps all the way to the end if clicking on some other citations. Maybe when users clicks on a paper which has no citation link, we could show them an option to navigate to the citation to the end of the paper, just to make sure that we are not interrupting their reading experience?

**Comment by andrewhead** [comment]
> Maybe when users clicks on a paper which has no citation link, we could show them an option to navigate to the citation to the end of the paper, just to make sure that we are not interrupting their reading experience?

I think this is a nice idea! I think this might be a good default behavior to keep in mind for #56
