### ISSUE TITLE
Include numeric subscripts and superscripts in symbols

### ISSUE THREAD

**Issue by andrewhead** [allenai/scholar-reader#41]
The bounding boxes for symbols currently don't include numeric subscripts and superscripts, but they probably should. This is to provide users with the right feel (to make it feel like the full symbol is getting highlighted). It's also important to include the superscript or subscript in the symbol in case it lends semantic meaning to the symbol.

As a concrete example, for arXiv paper `1811.12889`, only "s_k" gets highlighted when a user hovers over it, though we want the entirety of "s_k^3" to get highlighted.

![image](https://user-images.githubusercontent.com/2358524/74366437-de5ed480-4d84-11ea-8aca-bf7e443c003d.png)

Completion of this task requires:
- [ ] A change to the `get_symbols` method that extracts a symbol for `<mn>` numeric elements
- [ ] These numeric symbols get tagged with a property that they are numeric
- [ ] Make sure that numeric symbols are being added as children of the symbols that they are superscripts and subscripts to (this might already be implemented by default)
- [ ] Update the UI to make sure not to show bounding boxes for purely numeric symbols that are not children of other symbols (i.e. don't make a `1` or `0` interactive)

**Comment by zkirby** [comment]
Haha before I dive into this too much, can you quickly remind me the difference between a character tag and a symbol tag?

**Comment by zkirby** [comment]
Also slightly silly and nuanced but would we want to consider "1 + 2" a symbol (basically is a conjunction of multiple mn also a symbol)?

**Comment by zkirby** [comment]
The reason I ask the above is I kind of see two approaches to this: 
1) Look for any mn and given some heuristic, decide if this particular mn should be a symbol.
2) Look through the descendent tree of a tag we've decided should be a symbol and 'symbolize' all of the descendents that should also now be symbols.

**Comment by andrewhead** [comment]
> Haha before I dive into this too much, can you quickly remind me the difference between a character tag and a symbol tag?

Yeah, sure!

*Characters* are individual letters in the TeX for which we will detect the positions by coloring (e.g., in this case `x` or `2` in `x^2`. Character tags are any MathML tag that contains a single character that we will detect the position of.

*Symbols* are meaningful collections of *characters* that should be clickable in a paper. For instance `x^2`. Though `x` is also a symbol. Right now, we look for standalone letters (e.g., `<mi>x</mi>`), subscripts (e.g., `<msub>...</msub>`), and superscripts (`<msup>`) to indicate that all characters found within are part of the same "symbol".

For this PR, the code should recognize that:

* Numbers like `2` are characters
* `<msup>{mi element x}{mi element 2}</msup>` is a symbol
* The number `2` on its own is not a symbol

**Comment by andrewhead** [comment]
> Also slightly silly and nuanced but would we want to consider "1 + 2" a symbol (basically is a conjunction of multiple mn also a symbol)?

Good question! I think let's start with assuming it isn't. I can't imagine us wanting to make such a thing clickable, so we don't have to consider that a symbol.

**Comment by andrewhead** [comment]
> Look for any mn and given some heuristic, decide if this particular mn should be a symbol.

My feeling is that `mn` should be parts of symbols, though not symbols themselves.

> Look through the descendent tree of a tag we've decided should be a symbol and 'symbolize' all of the descendents that should also now be symbols.

Intriguing. Perhaps this would work too!
