### ISSUE TITLE
Fix up sentence splitting

### ISSUE THREAD

**Issue by andrewhead** [allenai/scholar-reader#65]
Our TeX sentence detector returns the wrong character offsets for sentences. This impacts the user experience, as we cannot detect the locations of sentences (and therefore make those sentences interactive) if we don't have accurate offsets for them in the TeX.

The cause of the issue is that when we call the `pysbd` for sentence splitting, the character offsets for the `start` of sentences are sometimes incorrect. Specifically, the `start` index is sometimes erroneously set to 0. See [this issue](https://github.com/nipunsadvilkar/pySBD/issues/49) for details about when and why this occurs.

**Spec**. In a single example, here's the desired behavior. When we run the following code:

```python
from entities.sentences.extractor import SentenceExtractor
extractor = SentenceExtractor()
sentences = extractor.parse(
    "filename.tex",
    "This is a sentence. Next we describe two items. 1) The first item. 2) The second item."
    )

for s in sentences:
    print(s)
```

We _don't_ want this behavior (the current, undesired, output):

```
Sentence(start=0, end=19, tex_path='filename.tex', id_='0', tex='This is a sentence.', context_tex='This is a sentence.', text='This is a sentence.')
Sentence(start=20, end=47, tex_path='filename.tex', id_='1', tex='', context_tex='', text='Next we describe two items.')
Sentence(start=0, end=18, tex_path='filename.tex', id_='2', tex='', context_tex='', text='1) The first item.')
Sentence(start=0, end=19, tex_path='filename.tex', id_='3', tex='', context_tex='', text='2) The second item.')
```

The _desired output_ is (note the corrected `start` and `end` indices of the 3rd and 4th sentences):

```
Sentence(start=0, end=19, tex_path='filename.tex', id_='0', tex='This is a sentence.', context_tex='This is a sentence.', text='This is a sentence.')
Sentence(start=20, end=47, tex_path='filename.tex', id_='1', tex='', context_tex='', text='Next we describe two items.')
Sentence(start=48, end=66, tex_path='filename.tex', id_='2', tex='', context_tex='', text='1) The first item.')
Sentence(start=67, end=86, tex_path='filename.tex', id_='3', tex='', context_tex='', text='2) The second item.')
```

**Implementation options**. The only requirements for this issue are that:

- [ ] We should still use pysbd, as it is a high-quality sentence splitter
- [ ] The sentence extractor returns the desired output above

Any technical solution that continues to use pysbd, but which works around this problem, is acceptable. One (probably too time-consuming) option is to submit a patch to pysbd.

I will outline one potential solution here, which I think would be pretty quick to implement. It just adjusts offsets for sentences with a start index of `0` based on a string search, starting after the last correctly-located sentence. Here's the pseudocode:

```
for sentence in [sentences extracted with pysbd]

  if (sentence is not the first sentence)

    if (sentence.start is 0)
      real-start := (search  full-tex-string, starting at last-sentence.end)
      real-end := (real-start) + (sentence.end - sentence.start)
      update sentence start and end to real-start and real-end

  last-sentence := sentence
```

Assumptions of this implementation are that:
1. There's a way to get a _ordered_ list of sentences from pysbd
2. The distance `end`-`start` for all sentences extracted from pysbd is correct. Because `start` isn't always correct, I don't know if the offset of `end` relative to `start` is always correct.

I don't know if these two assumptions hold. Before implementing this solution, the person handling this issue should make sure those assumptions hold, by experimenting with pysbd, and potentially by looking at the pysbd code base.

**Comment by zkirby** [comment]
A few comments before I push this PR up. 
It's hard to tell exactly how and when the sentence extractor will break. Following the comments provided by the creator in the linked issue does not fix all cases (although I had to come up with some somewhat arbitrary cases in order to break it). 

I can also only prove the first of our two assumptions and instead am relying on anecdotal evidence for the second assumption (although I have yet to come up with a case that does not work). 

What bothers me is that I can't figure out *why* the start and end are calculated the way they are. I'm assuming there must be a very valid reason, but I can't figure out why it's done is such an inconsistent way. I say this bc the sentence extractor appears to be extremely good at finding the sentences themselves. Thus, it's unclear to me why the start and end are not just calculated based on the length of the string and the end position of the previous string?

**Comment by andrewhead** [comment]
> I say this bc the sentence extractor appears to be extremely good at finding the sentences themselves.

Yeah, exactly! If only it had provided accurate character offsets for the sentences, we'd be golden!

> Thus, it's unclear to me why the start and end are not just calculated based on the length of the string and the end position of the previous string?

The reason I'm thinking of using `end` - `start` instead of the length of the extracted sentence is that I wasn't sure if `pysbd` does sanitization on the sentences that it returns (e.g., removing redundant whitespace or strangely-encoded characters). If we have a guarantee that it doesn't sanitize the strings it returns, then we can just use `len(sentence)` like you mentioned.

**Comment by andrewhead** [comment]
> I can also only prove the first of our two assumptions and instead am relying on anecdotal evidence for the second assumption (although I have yet to come up with a case that does not work).

Roger. While it would be great if we could come up with a bulletproof solution to this issue, if it's just not possible, we might be able to find something that works 99% of the time, and fix up other errors as our pipeline finds them.
