### ISSUE TITLE
Definition preview

### ISSUE THREAD

**Issue by andrewhead** [allenai/scholar-reader#95]
Some participants in our usability study frequently used the functionality of the symbol search prototype to go find the green-highlighted sentence. These users participants thought it would be easier for them to use the tool if there was some visual aid (e.g., a tooltip) that showed them the highlighted sentence as soon as they clicked on a symbol.

This issue includes two steps:
- [ ] Come up with a compelling design to satisfy this need. It might be a tooltip. It might just be a preview of the sentence that appears out-of-the-way, in the corner of the screen, which is easy to dismiss. 
- [ ] Implement that design.

**Comment by zkirby** [comment]
Notes after playing around with prototypes of both designs:
1. I feel strongly that a tool tip is not the right direction it really does feel like it disrupts the flow of reading an equation that is even remotely long. 
2. An out of the way tooltip does feel like a much better interaction however there is a caveat: it doesn't make much sense to display it when the green sentence is already visible on the page, however it also feels like it would be a bit strange if it didn't have the same interaction for every  symbol. 

I imagine there might be an interaction out there that possibly solves this issue. Maybe something where we make the green sentence itself 'sticky' in that if a symbol is highlighted and the green sentence is out of view or scrolls out of view, the sentence turns into a floating tooltip. I also imagine this would be much harder to implement tho

**Comment by andrewhead** [comment]
Integrated in https://github.com/allenai/scholar-reader/commit/9b5c8aed2b672ef39a0de526106a59e46d854a2a.

One issue is that, in this commit, rendering gets pretty gummy when one clicks on the page. I'm not sure why.
