### ISSUE TITLE
Navigation for symbol search

### ISSUE THREAD

**Issue by andrewhead** [allenai/scholar-reader#96]
Add symbol navigation that makes it easier for readers to go forward in back between instances of a symbol.

This issue requires:

- [x] a counter for how many symbols were matched and which one was selected (e.g., "6 of 16")
- [x] "next" button
- [x] "back" button
- [ ] hotkeys for each action

The navigation and search counter should probably be added to the PDF reader's toolbar, though this is up for discussion.

**Comment by zkirby** [comment]
I can start working on this issue :)

**Comment by andrewhead** [comment]
@zkirby I've been ruminating on our conversation from earlier. It occurs to me that we have at least these for implementing the "next / back" search widget. I'm pretty committed to getting our next / back button to use the same search interface as pdf.js's Ctrl+F search for consistency's sake (and because I think it will be hella confusing to users if they are allowed to conduct two parallel searches, one over text and one over symbols).

In my mind, the alternatives include at least:

1. Hook up to the pdf.js search widget. Clear the search widget of the prior text search whenever symbol search starts. Figure out a way to insert our count of matches into the search widget.

2. Disable the pdf.js widget, implement our _own_ search widget, and intercept signals from the pdf.js event bus that control our search widget when a user is doing a Ctrl+F search.

I'm secretly hoping that there's a 3rd option out there that's more elegant than either of these XD

**Comment by andrewhead** [comment]
I'm going to be logging some notes about how pdf.js "find" functionality works. First, it looks like there are two events on the event bus that are relevant: 'find' and 'updatefindmatchescount'

https://github.com/mozilla/pdf.js/blob/master/web/app.js#L1685-L1687

**Comment by andrewhead** [comment]
Second, it looks like the pdf.js viewer at some point provided support for providing your own find widget. Check out this pull request: https://github.com/mozilla/pdf.js/pull/2197

Based on a first look, it looks like one can define a unique 'ExternalServices' class for the app, which can be used to turn off the default Ctrl+F widget and substitute it with another. Here's [the default external services class](https://github.com/mozilla/pdf.js/blob/c218e94f664c97d3c95994d57b11d11488dae54b/web/app.js#L89)), and I hypothesize that we may be able to connect it to a custom "Find" widget by overriding `supportsIntegratedFind`, `updateFindControlState`, and `updateFindMatchesCount`

**Comment by andrewhead** [comment]
Meanwhile, the [pdf_find_controller.js](https://github.com/mozilla/pdf.js/blob/master/web/pdf_find_controller.js) file looks pretty complex. It's a good indication that, especially for text search, if we don't have to rewrite the text-finding logic we will save ourselves a ton of time.

**Comment by andrewhead** [comment]
I've managed to hook into pdf.js find functionality from outside of pdf.js. The fix was, first, updating `genericcom.js` as described above to add external find handlers: https://github.com/andrewhead/pdf.js/commit/bd9255f81c75d75acd83943778cbf8149b48f59d

This can be tested out by cloning `andrewhead/pdf.js`, and then:

1. `npm install`
2. `gulp server`
3. Open `localhost:8888/web/viewer.html` in the browser
4. Open the web console
5. Execute the command: `window.dispatchEvent(new CustomEvent("find", { detail: { query: "language" }}))`

This last command simulates one of the many `find` commands that can be submitted to the pdf.js-internal find controller (see a more complete listing in that `genericcom.js` file)

It seems to me that the right next steps for this issue is to:

1. Make minimal changes to the pdf.js `genericcom.js` code to act as a gateway for find events
2. Add a React find widget that emits events in a way that `genericcom.js` can detect and forward to the pdf.js find controller; then update that React find widget to update its presentation with updates from the pdf.js find controller

And then, after these two steps are finished, updating the React widget to also control going back and forward over symbols in papers.

**Comment by zkirby** [comment]
Awesome, thank you for the detailed starting point! :).

Just to make sure I understand what the desired behavior is, we expect when the users presses CTRL+F one of two things happens:
----
1. If there is no symbol selected - they are presented with the default find functionality currently present in pdf.js
2. If there is a symbol selected, or if they select a symbol with search open, a count appears instead of the string search and they can next/back through the existing symbol list

Or it might be helpful if you break down exactly what the interaction would be hahaha, I think I'm still a little confused how exactly a user initiates symbol search.

**Comment by andrewhead** [comment]
This is pretty close! The idea is there's 1 search widget, supporting 2 search interactions:

*Interaction 1: Text Search*: User types Ctrl+F. This opens up the search widget. The user can then click "next" and "back" buttons to go to the next and previous matches.

*Interaction 2: Symbol Search*: User clicks a symbol. This opens up the search widget. The user can then click "next" and "back" buttons to go to the next and previous matches. The typical input field for the search widget is replaced with a set of filters that can be used to fine-tune what parts of the symbol will be searched for (which should be implemented in #93).

In both cases, the search widget shows the count of matches, and the index of the currently selected match. Ctrl+F will only initiate text search.

Does that make sense? Can you think of other compelling ways to implement the interaction?

**Comment by andrewhead** [comment]
@zkirby I just added a starting point for a new find-bar that we can use for this PR. Let's do both of our development on the find-bar branch which contains the new find bar (the branch is https://github.com/allenai/scholar-reader/tree/find-bar). The find bar looks like this:

![image](https://user-images.githubusercontent.com/2358524/79674374-728b5480-8197-11ea-9683-87f8c46e5650.png)

We can style it up once we have the right behavior implemented!

**Comment by andrewhead** [comment]
@zkirby I updated the find bar to plug into pdf.js's find functionality, see GIF right below:

![search_functionality](https://user-images.githubusercontent.com/2358524/79677557-8ccd2e80-81a7-11ea-859b-bfd5b5d0149d.gif)

The updated code for the find bar is in the `find-bar` branch.

So this means all you should need to think about is extending the [`FindBar`](https://github.com/allenai/scholar-reader/blob/find-bar/ui/src/FindBar.tsx) component to also support symbol search. It should use the same state variables (e.g., `currentMatch` and `matchCount`). Though you may need to move those variables into `ScholarReaderContext` to get the job done. Lmk if you want to discuss any implementation ideas!

**Comment by zkirby** [comment]
Awesome, I'll take a look :)

**Comment by zkirby** [comment]
Hey quick follow up, what is the difference between an annotation and an entity?

**Comment by zkirby** [comment]
Okay so I've spent a few hours writing some initial code and laying everything out and I think it should be very very doable to have the behavior as you've described. However, I have a few followup question that should help me finish off this PR :).
1. What is the difference between an entity and an annotation? Why is there a difference, and when should an entity id be used versus an annotation id? (I understand we will need to map between these in order for the finder to actually be able to fully work but I want to make sure I fully understand them)
2. Should one take priority, string search or symbol search? I.e., if I am in the middle of a symbol search, if I press ctrl+f should it unselect the selected symbol, keep the symbol selected but switch to string search, or do nothing until the symbol is deselected?

Thanks!

**Comment by andrewhead** [comment]
Good questions!

> What is the difference between an entity and an annotation?

Entities are a type of object that was found in the paper. Symbols, citations, and sentences are all entities.  Each one corresponds to a single row in one of the database's entity tables (e.g., the `symbol`, `citation`, or `sentence` table). The only way to show the position of an entity, currently, is by creating an annotation for it.

Annotations are highlights that show the locations of entities, and make information about entities available when the annotation is clicked. Usually there will be one annotation for each entity. The `PageOverlay` loops through lists of entities, creating an annotation for each entity.

> Should one take priority, string search or symbol search?

My gut instinct is that both searches should interrupt each other. That means:

* I Ctrl+F in the middle of a symbol search, that symbol should be deselected and text search should begin.
* If I click on a symbol during text search, the text search box should be emptied and symbol search should begin.

That said, I'm open to other ideas! That's just my first guess about what might might feel good to a user.

**Comment by zkirby** [comment]
Interesting, what is the use case for having both annotation ids and symbol ids?

**Comment by andrewhead** [comment]
While I believe I had a good reason at some point in the past, I don't have one right now ^)^

**Comment by andrewhead** [comment]
One reason I separated it out into two IDs is that, previously, components could only figure out what entity was selected by parsing the ID for the selected annotation, which felt brittle. That led me to instead add explicit properties to the scholar reader state for what type of entity was selected, so we wouldn't need to duplicate the code for parsing annotation IDs to get entity IDs everywhere.

**Comment by andrewhead** [comment]
A future version of this tool will order symbols not by their position in the paper, but by the order they appear in the PDF markup or the LaTeX (i.e., in prose order, so that the search results don't dart back and forth between parallel columns). Here are some snippets that should be useful for doing this.

```typescript
  const areSymbolsAlignedToSentences = symbols.all.some((sId) => {
    symbols.byId[sId].sentence !== null;
  });

  let symbolsToSort;
  if (areSymbolsAlignedToSentences) {
    symbolsToSort = symbols.all.filter((sId) => {
      symbols.byId[sId].sentence !== null;
    });
  } else {
    symbolsToSort = [...symbols.all];
  }

  ...

  // I don't know if the signs returned are correct yet.
  const sorted = [...symbolIds];
  sorted.sort((sId1, sId2) => {
    const sentenceId1 = symbols.byId[sId1].sentence;
    const sentenceId2 = symbols.byId[sId2].sentence;
    if (sentenceId1 === null || sentenceId2 === null) {
      return 0;
    }
    const sentence1 = sentences.byId[sentenceId1];
    const sentence2 = sentences.byId[sentenceId2];
    return sentence1.index - sentence2.index;
  });
```
